-- Analytics tables for visits + lead funnel events

CREATE TABLE IF NOT EXISTS `analytics_visits` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `request_id` VARCHAR(64) NULL,
  `ip` VARCHAR(45) NULL,
  `method` VARCHAR(10) NULL,
  `scheme` VARCHAR(10) NULL,
  `host` VARCHAR(190) NULL,
  `uri` TEXT NULL,
  `path` VARCHAR(512) NULL,
  `query_string` TEXT NULL,
  `get_params_json` LONGTEXT NULL,
  `request_headers_json` LONGTEXT NULL,
  `referrer` TEXT NULL,
  `referrer_host` VARCHAR(190) NULL,
  `source_type` VARCHAR(32) NULL,
  `user_agent` TEXT NULL,
  `device_type` VARCHAR(16) NULL,
  `is_bot` TINYINT(1) NOT NULL DEFAULT 0,
  `accept_language` VARCHAR(255) NULL,
  `country_iso2` CHAR(2) NULL,
  `country_name` VARCHAR(120) NULL,
  `city_name` VARCHAR(120) NULL,
  `timezone` VARCHAR(64) NULL,
  `latitude` DECIMAL(10,7) NULL,
  `longitude` DECIMAL(10,7) NULL,
  `session_id` VARCHAR(128) NULL,
  `user_id` BIGINT UNSIGNED NULL,
  `utm_source` VARCHAR(190) NULL,
  `utm_medium` VARCHAR(190) NULL,
  `utm_campaign` VARCHAR(190) NULL,
  `utm_term` VARCHAR(190) NULL,
  `utm_content` VARCHAR(190) NULL,
  `search_query` VARCHAR(190) NULL,
  `visited_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_analytics_visits_visited_at` (`visited_at`),
  KEY `idx_analytics_visits_ip` (`ip`),
  KEY `idx_analytics_visits_user_id` (`user_id`),
  KEY `idx_analytics_visits_country` (`country_iso2`),
  KEY `idx_analytics_visits_source` (`source_type`),
  KEY `idx_analytics_visits_search_query` (`search_query`),
  KEY `idx_analytics_visits_device` (`device_type`),
  KEY `idx_analytics_visits_path` (`path`),
  KEY `idx_analytics_visits_ref_host` (`referrer_host`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `analytics_lead_events` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `request_id` VARCHAR(64) NULL,
  `event_type` VARCHAR(64) NOT NULL,
  `user_id` BIGINT UNSIGNED NULL,
  `email` VARCHAR(190) NULL,
  `subscription_id` BIGINT UNSIGNED NULL,
  `plan_id` BIGINT UNSIGNED NULL,
  `amount_usd` DECIMAL(28,12) NULL,
  `currency_code` VARCHAR(16) NULL,
  `amount_in_currency` DECIMAL(28,12) NULL,
  `ip` VARCHAR(45) NULL,
  `user_agent` TEXT NULL,
  `session_id` VARCHAR(128) NULL,
  `host` VARCHAR(190) NULL,
  `path` VARCHAR(512) NULL,
  `referrer_host` VARCHAR(190) NULL,
  `source_type` VARCHAR(32) NULL,
  `utm_source` VARCHAR(190) NULL,
  `utm_medium` VARCHAR(190) NULL,
  `utm_campaign` VARCHAR(190) NULL,
  `utm_term` VARCHAR(190) NULL,
  `utm_content` VARCHAR(190) NULL,
  `search_query` VARCHAR(190) NULL,
  `meta_json` LONGTEXT NULL,
  `event_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_analytics_leads_event_time` (`event_time`),
  KEY `idx_analytics_leads_type` (`event_type`),
  KEY `idx_analytics_leads_user` (`user_id`),
  KEY `idx_analytics_leads_subscription` (`subscription_id`),
  KEY `idx_analytics_leads_source_type` (`source_type`),
  KEY `idx_analytics_leads_referrer_host` (`referrer_host`),
  KEY `idx_analytics_leads_utm_source` (`utm_source`),
  KEY `idx_analytics_leads_utm_campaign` (`utm_campaign`),
  KEY `idx_analytics_leads_search_query` (`search_query`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
