SET NAMES utf8mb4;

UPDATE `seo_generator_settings`
SET `settings_json` = JSON_SET(
  `settings_json`,
  '$.campaigns',
  JSON_MERGE_PATCH(
    COALESCE(JSON_EXTRACT(`settings_json`, '$.campaigns'), JSON_OBJECT()),
    JSON_EXTRACT('{
      "reviews": {
        "key": "reviews",
        "title": "Reviews",
        "title_ru": "Обзоры",
        "description": "Real reviews, comparisons and shortlists for affiliate tools, vendors and working stacks.",
        "description_ru": "Реальные обзоры, сравнения и подборки по инструментам, поставщикам и рабочим стекам для арбитража.",
        "material_section": "reviews",
        "enabled": true,
        "daily_min": 4,
        "daily_max": 8,
        "max_per_run": 3,
        "duplicate_retry_attempts": 2,
        "word_min": 1800,
        "word_max": 4200,
        "seed_salt_suffix": "reviews",
        "styles_en": [
          "comparison review",
          "tool benchmark",
          "provider shortlist",
          "buyer guide",
          "stack review",
          "field comparison",
          "decision matrix",
          "vendor radar",
          "pricing teardown",
          "use-case match review",
          "workflow fit review",
          "support quality audit",
          "scaling stress test",
          "operator verdict",
          "category leaderboard",
          "best-for list",
          "procurement memo",
          "migration comparison",
          "cost-of-stack review",
          "hands-on test note"
        ],
        "styles_ru": [
          "сравнительный обзор",
          "бенчмарк инструментов",
          "шортлист поставщиков",
          "buyer guide",
          "разбор стека",
          "полевое сравнение",
          "матрица выбора",
          "радар поставщиков",
          "разбор ценообразования",
          "обзор fit под use-case",
          "разбор fit в workflow",
          "аудит качества саппорта",
          "стресс-тест на масштаб",
          "вердикт оператора",
          "лидерборд категории",
          "подборка best-for",
          "мемо по закупке",
          "сравнение для миграции",
          "обзор стоимости стека",
          "заметка по hands-on тесту"
        ],
        "clusters_en": [
          "affiliate networks and partner programs",
          "cloaking tools and routing stacks",
          "tracker platforms and attribution quality",
          "ai generators for creatives and workflows",
          "server providers and hosting reliability",
          "domain registrars and domain vendors",
          "anti-detect browsers and operator environments",
          "spy tools and ad intelligence suites",
          "proxy providers and mobile proxy pools",
          "landing builders and page infrastructure",
          "payment tools and routing helpers",
          "telegram tools and team utilities",
          "hosting panels and deployment workflows",
          "cdn and edge delivery for landers",
          "analytics dashboards and reporting layers",
          "team knowledge bases and SOP tools",
          "creative storage and asset pipelines",
          "link rotators and redirect managers",
          "captcha solving services and automation helpers",
          "warmup tools and account farming utilities",
          "offer intelligence and payout comparison tools",
          "notification systems and alerting stacks",
          "moderation monitoring and compliance helpers",
          "comment management and community tools",
          "crm tools for affiliate operators",
          "checkout recovery and conversion helpers",
          "template libraries and landing kits",
          "browser automation and QA helpers",
          "content generation assistants for operators",
          "geo-routing and localization helpers"
        ],
        "clusters_ru": [
          "партнерки и affiliate-сети",
          "клоаки и routing-стеки",
          "трекеры и качество атрибуции",
          "ИИ-генераторы для креативов и workflow",
          "серверные провайдеры и надежность хостинга",
          "регистраторы доменов и доменные поставщики",
          "anti-detect браузеры и среда оператора",
          "spy-сервисы и ad-intelligence наборы",
          "proxy-поставщики и mobile proxy-пулы",
          "конструкторы лендингов и инфраструктура страниц",
          "платежные сервисы и routing helpers",
          "Telegram-инструменты и утилиты команды",
          "панели хостинга и workflow деплоя",
          "CDN и edge-доставка для лендингов",
          "аналитические дашборды и reporting-слой",
          "базы знаний команды и SOP-инструменты",
          "хранилища креативов и asset-пайплайны",
          "ротаторы ссылок и redirect-менеджеры",
          "сервисы решения captcha и automation helpers",
          "warmup-инструменты и утилиты для фарма аккаунтов",
          "сервисы по офферам и сравнению payout",
          "системы уведомлений и alerting-стеки",
          "мониторинг модерации и compliance-инструменты",
          "сервисы комментариев и community-утилиты",
          "CRM для affiliate-операторов",
          "checkout-recovery и conversion helpers",
          "библиотеки шаблонов и landing-kits",
          "browser-automation и QA-утилиты",
          "content-assist инструменты для операторов",
          "geo-routing и localization helpers"
        ],
        "article_structures_en": [
          "Category -> evaluation criteria -> shortlist -> comparison table -> recommendation",
          "Use case -> stack candidates -> benchmarks -> tradeoffs -> verdict",
          "Problem -> providers -> strengths and weaknesses -> risk notes -> best fit",
          "Need -> operator constraints -> candidate stack -> elimination logic -> final pick",
          "Budget tier -> options -> hidden costs -> scaling ceiling -> recommendation",
          "Scenario -> review criteria -> top picks -> red flags -> deployment notes",
          "Role-based review -> who needs it -> best options -> workflow fit -> conclusion",
          "Benchmark setup -> measured results -> interpretation -> tradeoffs -> operator verdict",
          "Migration path -> current pain -> replacement options -> switching cost -> recommendation",
          "Comparison table -> strongest use cases -> support and pricing -> final shortlist",
          "Field test -> onboarding -> daily usage -> failure modes -> verdict",
          "Best-for ranking -> category leaders -> edge cases -> who should skip -> close",
          "Procurement memo -> must-have criteria -> vendor review -> negotiation points -> recommendation",
          "Stack layer -> available tools -> compatibility notes -> risk map -> final shortlist",
          "Problem map -> tool classes -> best fit by team maturity -> recommendation"
        ],
        "article_structures_ru": [
          "Категория -> критерии оценки -> шортлист -> таблица сравнения -> рекомендация",
          "Use-case -> кандидаты в стек -> бенчмарки -> tradeoffs -> вердикт",
          "Проблема -> провайдеры -> сильные и слабые стороны -> риски -> лучший fit",
          "Потребность -> ограничения оператора -> кандидаты в стек -> логика отсева -> финальный выбор",
          "Бюджетный уровень -> варианты -> скрытые расходы -> потолок масштаба -> рекомендация",
          "Сценарий -> критерии обзора -> лучшие варианты -> red flags -> заметки по внедрению",
          "Обзор по ролям -> кому подходит -> лучшие опции -> fit в workflow -> вывод",
          "Схема бенчмарка -> измеренные результаты -> интерпретация -> tradeoffs -> вердикт оператора",
          "Путь миграции -> текущая боль -> варианты замены -> стоимость перехода -> рекомендация",
          "Таблица сравнения -> сильные use-case -> саппорт и цены -> финальный шортлист",
          "Полевой тест -> онбординг -> ежедневное использование -> failure modes -> вердикт",
          "Рейтинг best-for -> лидеры категории -> edge cases -> кому не подходит -> итог",
          "Мемо по закупке -> must-have критерии -> обзор вендоров -> точки переговоров -> рекомендация",
          "Слой стека -> доступные инструменты -> совместимость -> карта рисков -> финальный шортлист",
          "Карта проблемы -> классы инструментов -> fit по зрелости команды -> рекомендация"
        ],
        "article_system_prompt_en": "",
        "article_system_prompt_ru": "",
        "article_user_prompt_append_en": "Write real reviews, comparisons and curated shortlists for affiliate operators. Compare tools and vendors by concrete criteria: routing reliability, moderation resilience, attribution quality, pricing logic, onboarding friction, geo-fit, support quality, scaling limits, hidden risks and who each option is actually for. External resources are allowed when useful.",
        "article_user_prompt_append_ru": "Пиши реальные обзоры, сравнения и подборки для affiliate-операторов. Сравнивай инструменты и поставщиков по конкретным критериям: надежность routing, устойчивость под модерацией, качество атрибуции, логика цен, сложность онбординга, fit по гео, качество саппорта, ограничения по масштабу, скрытые риски и для кого подходит каждый вариант. В этом разделе допустимы ссылки на сторонние ресурсы, если они помогают обзору."
      }
    }', '$')
  )
)
WHERE `id` = 1;

