UPDATE seo_generator_settings
SET settings_json = JSON_SET(
    settings_json,
    '$.daily_min', 6,
    '$.daily_max', 14,
    '$.max_per_run', 20,
    '$.word_min', 1400,
    '$.word_max', 4200,
    '$.auto_expand_retries', 8,
    '$.expand_context_chars', 24000,
    '$.prompt_version', 'cpalnya-generator-v2-variance',
    '$.tone_variability', 84,
    '$.topic_analysis_limit', 500,
    '$.topic_analysis_user_prompt_append', 'Prioritize CPA, affiliate operations, media buying workflows, trackers, creatives, moderation, farm, source volatility and 2026 platform shifts. Expand aggressively into policy shifts, CIS regulation, platform enforcement, Telegram distribution, buyer routines, anti-ban behavior, tracking failures, payment fragility, routing, recovery scenarios, operator folklore, memeable pain points and backstage team systems. Avoid generic SaaS, fintech, antifraud and enterprise architecture angles unless they are directly tied to affiliate operations.',
    '$.article_user_prompt_append_ru', 'Пиши как редакция ниши, а не как SEO-генератор. Центр тяжести: арбитраж трафика, affiliate-операции, медиабаинг, farm, креативы, трекинг, postback, moderation, source volatility, handoff между ролями, Telegram-distribution, performance-команды, backstage-процессы и рыночные сдвиги. Каждый материал должен иметь собственный угол, собственную операционную задачу, собственный набор рисков и собственный практический вывод. Избегай перефразирования уже опубликованных материалов.',
    '$.expand_user_prompt_append_ru', 'При расширении статьи запрещено повторять уже существующие тезисы, подзаголовки, списки и заходы. Добавляй только новые детали: edge cases, failure modes, anti-patterns, QA checks, rollback-план, handoff-риски, операционные tradeoffs и прикладные решения.',

    '$.campaigns.journal.daily_min', 6,
    '$.campaigns.journal.daily_max', 12,
    '$.campaigns.journal.max_per_run', 4,
    '$.campaigns.journal.word_min', 1800,
    '$.campaigns.journal.word_max', 3600,
    '$.campaigns.journal.styles_ru', JSON_ARRAY(
        'редакционный разбор',
        'аналитическая записка',
        'trend briefing',
        'стратегический обзор',
        'открывающая статья номера',
        'обзор ниши',
        'редакционная колонка',
        'market memo',
        'policy-to-operations разбор',
        'operator column',
        'редакционное эссе',
        'сигнальный обзор рынка',
        'карта изменений ниши',
        'backstage-разбор индустрии',
        'разбор сдвига платформы',
        'market-intelligence записка'
    ),
    '$.campaigns.journal.clusters_ru', JSON_ARRAY(
        'Meta Ads в 2026: фарм, BM-устойчивость и антибан',
        'TikTok и short-form воронки под affiliate-офферы',
        'Telegram Mini Apps, комьюнити и retention в арбитраже',
        'AI-креативы, compliance и контроль prompt-пайплайна',
        'трекеры, атрибуция и потеря сигналов после privacy-сдвигов',
        'сдвиги спроса по nutra, finance, iGaming и crypto в 2026',
        'карта ниши affiliate в 2026',
        'устройство operator/backstage систем внутри команд',
        'новая дисциплина медиабаинга после policy-сдвигов',
        'срок жизни связок и что его действительно сокращает',
        'почему команды теряют контроль на этапе handoff',
        'контур решений после деградации signal quality',
        'Telegram как редакционная и дистрибуционная среда',
        'creative shelf life и экономика постоянной пересборки',
        'platform trust как операционный ресурс команды',
        'тихие рыночные сдвиги, которые замечают слишком поздно'
    ),
    '$.campaigns.journal.article_structures_ru', JSON_ARRAY(
        'Краткий тренд -> что изменилось -> кто выигрывает -> операционные выводы -> чеклист',
        'Сдвиг источника -> риски -> адаптация -> примеры -> следующие шаги',
        'Миф и реальность -> факты -> рабочие сигналы -> вывод',
        'Открывающая статья номера -> контекст ниши -> backstage-инсайты -> выводы для оператора -> итог',
        'Сигнал рынка -> разбор причин -> затронутые роли -> последствия -> решение',
        'Контекст -> что ломается -> как команды отвечают -> практический вывод',
        'Редакционный хук -> карта напряжения -> кто под ударом -> что делать -> closing note',
        'Наблюдение -> данные и симптомы -> интерпретация -> прикладные действия -> вывод'
    ),
    '$.campaigns.journal.article_user_prompt_append_ru', 'Фокус на трендах арбитража трафика, операционных решениях команды, качестве сигналов, платформенных сдвигах и прикладных стратегических выводах. Если тема уже затрагивалась, находи новый угол: другой гео-контекст, другую роль, другой tradeoff, другой слой backstage-операционки.',

    '$.campaigns.playbooks.daily_min', 8,
    '$.campaigns.playbooks.daily_max', 16,
    '$.campaigns.playbooks.max_per_run', 6,
    '$.campaigns.playbooks.word_min', 1600,
    '$.campaigns.playbooks.word_max', 4200,
    '$.campaigns.playbooks.styles_ru', JSON_ARRAY(
        'пошаговый how-to',
        'гайд по устранению проблем',
        'операционный playbook',
        'технический кейс',
        'setup memo',
        'launch checklist',
        'runbook',
        'SOP для команды',
        'операционная инструкция',
        'postmortem с решением',
        'troubleshooting memo',
        'guide for operators',
        'рабочая записка',
        'implementation guide',
        'handoff playbook',
        'zero-to-launch разбор'
    ),
    '$.campaigns.playbooks.clusters_ru', JSON_ARRAY(
        'настройка и прогрев Facebook farm',
        'cloaking и безопасная маршрутизация под модерацию',
        'tracker postback-шаблоны, макросы и отладка',
        'anti-detect браузеры, роли команды и SOP',
        'матрица тестирования креативов и цикл итераций',
        'платежки, домены, хостинг и восстановление лендингов',
        'шаблоны handoff и документация оператора',
        'day one setup для нового медиабайера',
        'QA перед запуском и контроль мелких сбоев',
        'прогрев trust у аккаунтов и BM без хаоса',
        'routing и резервная инфраструктура при сбое',
        'что делать после потери атрибуции',
        'creative review loop и устранение выгорания',
        'разбор командной рутины launch-дня',
        'миграция связки между командами без потери контекста',
        'полевые anti-patterns в ежедневной операционке'
    ),
    '$.campaigns.playbooks.article_structures_ru', JSON_ARRAY(
        'Проблема -> prerequisites -> точные шаги -> типовые фейлы -> проверка',
        'Цель -> стек -> внедрение -> код/настройки -> rollback-план',
        'Контекст кейса -> сетап -> метрики -> узкие места -> переиспользуемый шаблон',
        'Чеклист -> стек -> действия -> QA -> заметки по масштабу -> итог',
        'Сбой -> диагностика -> фиксы -> контроль результата -> safeguard',
        'Задача -> ограничения -> точная последовательность -> edge cases -> финальный SOP',
        'Стартовая точка -> implementation -> failure modes -> recovery -> handoff',
        'Наблюдение -> решение -> контроль -> масштабирование -> что не делать'
    ),
    '$.campaigns.playbooks.article_user_prompt_append_ru', 'Смещай акцент в сторону практической реализации, troubleshooting, SOP, handoff, rollback, QA и точных шагов оператора. Если тема уже встречалась, выбирай более узкий и новый угол: другой failure mode, другой этап пайплайна, другой тип команды, другой контекст запуска или другой источник сбоя.',

    '$.campaigns.signals.daily_min', 4,
    '$.campaigns.signals.daily_max', 10,
    '$.campaigns.signals.max_per_run', 4,
    '$.campaigns.signals.word_min', 1400,
    '$.campaigns.signals.word_max', 3000,
    '$.campaigns.signals.styles_ru', JSON_ARRAY(
        'policy brief',
        'обзор сигнала рынка',
        'регуляторная записка',
        'сводка изменений платформ',
        'news-analysis memo',
        'операционный сигнал',
        'platform watch',
        'enforcement-разбор',
        'регуляторный радар',
        'briefing по сдвигу платформы',
        'risk note',
        'командная записка о сдвиге',
        'market signal memo',
        'разбор давления compliance',
        'операционный policy digest',
        'сигнальная колонка'
    ),
    '$.campaigns.signals.clusters_ru', JSON_ARRAY(
        'изменения policy в Meta и ужесточение модерации',
        'сдвиги Telegram, правила монетизации и новые ограничения',
        'ограничения TikTok Ads и апдейты commerce-экосистемы',
        'регуляторные движения в СНГ и их эффект на affiliate-рынок',
        'privacy-сдвиги в мире и последствия для атрибуции',
        'сигналы по payment, compliance и волатильности источников',
        'новые enforcement-паттерны и их ранние признаки',
        'перестройка risk-profile у источников трафика',
        'давление платформ на креативные пайплайны',
        'что меняется в trust-модели аккаунтов',
        'регуляторный фон и операционная цена решений',
        'новые риски для checkout, payments и domains',
        'почему вчерашние safe-ходы перестают работать',
        'глобальные policy-волны и их локальный эффект на СНГ',
        'рыночные сигналы, которые первыми чувствуют баеры',
        'сдвиги platform governance, которые нельзя игнорировать'
    ),
    '$.campaigns.signals.article_structures_ru', JSON_ARRAY(
        'Сигнал -> что изменилось -> влияние на оператора -> затронутые гео -> чеклист действий',
        'Policy-апдейт -> паттерн enforcement -> скрытые риски -> план реакции',
        'Новость -> почему это важно -> кто почувствует первым -> шаги смягчения',
        'Апдейт платформы -> реальные последствия -> зоны риска -> тактика команды',
        'Контекст -> новый риск -> что ломается -> как перестраиваться -> итог',
        'Регуляторный сдвиг -> где ударит -> как читать заранее -> практический вывод',
        'Сигнал -> интерпретация -> affected roles -> adaptation map -> next step',
        'Фон рынка -> новый pressure point -> что делать сейчас -> что отложить'
    ),
    '$.campaigns.signals.article_user_prompt_append_ru', 'Отслеживай policy, модерацию, регуляторику и рыночные сигналы вокруг арбитража трафика. Каждый материал должен отвечать на вопрос: что это меняет для команды прямо сейчас, где растет риск, и какое конкретное решение нужно принять раньше конкурентов.',

    '$.campaigns.fun.daily_min', 2,
    '$.campaigns.fun.daily_max', 6,
    '$.campaigns.fun.max_per_run', 3,
    '$.campaigns.fun.word_min', 1000,
    '$.campaigns.fun.word_max', 2400,
    '$.campaigns.fun.styles_ru', JSON_ARRAY(
        'сатирический памфлет',
        'юмористический обзор',
        'мем-редакционка',
        'операционная пародия',
        'иронический backstage-разбор',
        'фельетон ниши',
        'мемный кейсовый формат',
        'саркастический operator column',
        'трагикомедия модерации',
        'редакционная шутка с фактами',
        'пародийный портрет роли',
        'операционный стендап-текст',
        'юмористический postmortem',
        'нишевая сатира',
        'абсурдный обзор дня',
        'внутренний фольклор команды'
    ),
    '$.campaigns.fun.clusters_ru', JSON_ARRAY(
        'агентская жизнь и фольклор медиабаеров',
        'драма фарма и суеверия операторов',
        'выгорание креативов как темная комедия',
        'хаос трекеров и абсурд postback-ошибок',
        'командные мемы и backstage-ритуалы',
        'модерация платформ как трагикомедия',
        'ритуалы launch-дня и коллективные неврозы',
        'ночная смена баеров как отдельный жанр',
        'вечная охота на виноватого после сбоя',
        'фарм как мифология и бытовая магия',
        'Telegram-фольклор affiliate-команд',
        'креативные созвоны как производственный театр',
        'пародии на operator-архетипы',
        'когда compliance приходит как персонаж хоррора',
        'внутренние легенды о postback и атрибуции',
        'бытовой абсурд рынка, который слишком узнаваем'
    ),
    '$.campaigns.fun.article_structures_ru', JSON_ARRAY(
        'Сетап -> абсурдное обострение -> панчлайн -> нишевая правда',
        'Портрет персонажа -> операционный хаос -> мемный payoff -> вывод',
        'Пародийный обзор -> преувеличение -> реальные боли -> финальный укол',
        'Обычная ситуация -> escalation -> комический слом -> узнаваемый итог',
        'Мемный кейс -> backstage-правда -> абсурд -> мораль',
        'Сцена команды -> конфликт -> гротеск -> точный вывод',
        'Наблюдение -> шутка -> распознаваемая боль -> closing line',
        'Фольклор ниши -> смешная оболочка -> реальная проблема -> punchline'
    ),
    '$.campaigns.fun.article_user_prompt_append_ru', 'Держи тон живым, ироничным и нишевым. Юмор должен рождаться из реальной affiliate-операционки, а не из общих шуток. Даже развлекательный текст должен нести узнаваемую правду ниши и не повторять уже существующие мем-углы и сюжеты.'
)
WHERE id = 1;
