UPDATE seo_generator_settings
SET settings_json = JSON_SET(
    settings_json,
    '$.prompt_version', 'cpalnya-generator-v2-variance',
    '$.daily_min', 6,
    '$.daily_max', 16,
    '$.max_per_run', 20,
    '$.duplicate_retry_attempts', 2,
    '$.word_min', 1400,
    '$.word_max', 4200,
    '$.auto_expand_retries', 8,
    '$.expand_context_chars', 24000,
    '$.topic_analysis_limit', 500,
    '$.tone_variability', 84,
    '$.article_user_prompt_append_ru', 'Пиши как редакция ниши, а не как механический SEO-генератор. Каждый материал должен иметь собственный угол, собственную практическую задачу, собственный набор tradeoff и собственный прикладной вывод. Запрещено перефразировать уже существующие статьи и повторять один и тот же тезис под новым подзаголовком.',
    '$.expand_user_prompt_append_ru', 'При расширении запрещено повторять уже сказанные тезисы, подзаголовки и списки. Добавляй только новые практические детали: edge cases, failure modes, anti-patterns, QA checks, rollback-план, handoff-риски, operational tradeoff и понятные действия для команды.',
    '$.topic_analysis_user_prompt_append', 'Prioritize CPA, affiliate operations, media buying workflows, trackers, creatives, moderation, farm, source volatility and 2026 platform shifts. Expand aggressively into policy shifts, CIS regulation, platform enforcement, Telegram distribution, buyer routines, anti-ban behavior, tracking failures, payment fragility, routing, recovery scenarios, operator folklore, memeable pain points and backstage team systems. Avoid generic SaaS, fintech, antifraud and enterprise architecture angles unless they are directly tied to affiliate operations.',

    '$.campaigns.journal.daily_min', 6,
    '$.campaigns.journal.daily_max', 12,
    '$.campaigns.journal.max_per_run', 4,
    '$.campaigns.journal.duplicate_retry_attempts', 1,
    '$.campaigns.journal.word_min', 1800,
    '$.campaigns.journal.word_max', 3600,
    '$.campaigns.journal.styles_ru', JSON_ARRAY(
        'редакционный разбор',
        'аналитическая записка',
        'trend briefing',
        'стратегический обзор',
        'открывающая статья номера',
        'обзор ниши',
        'редакционная колонка',
        'market memo',
        'policy-to-operations разбор',
        'operator column',
        'редакционное эссе',
        'сигнальный обзор рынка'
    ),
    '$.campaigns.journal.article_structures_ru', JSON_ARRAY(
        'Краткий тренд -> что изменилось -> кто выигрывает -> операционные выводы -> чеклист',
        'Сдвиг источника -> риски -> адаптация -> примеры -> следующие шаги',
        'Миф и реальность -> факты -> рабочие сигналы -> вывод',
        'Открывающая статья номера -> контекст ниши -> backstage-инсайты -> выводы для оператора -> итог',
        'Наблюдение редакции -> симптомы рынка -> скрытая механика -> последствия для команды -> решение',
        'Сигнал -> кто почувствует первым -> что сломается -> как адаптироваться -> итог'
    ),
    '$.campaigns.journal.article_user_prompt_append_ru', 'Фокус на трендах арбитража трафика 2026, операционных решениях команды, качестве сигналов, платформенных сдвигах и прикладных стратегических выводах. Если тема уже затрагивалась, находи новый угол: другой гео-контекст, другую роль, другой tradeoff, другой слой backstage-операционки.',

    '$.campaigns.playbooks.daily_min', 8,
    '$.campaigns.playbooks.daily_max', 16,
    '$.campaigns.playbooks.max_per_run', 6,
    '$.campaigns.playbooks.duplicate_retry_attempts', 1,
    '$.campaigns.playbooks.word_min', 1600,
    '$.campaigns.playbooks.word_max', 4200,
    '$.campaigns.playbooks.styles_ru', JSON_ARRAY(
        'пошаговый how-to',
        'гайд по устранению проблем',
        'операционный playbook',
        'технический кейс',
        'setup memo',
        'launch checklist',
        'runbook',
        'operator SOP',
        'troubleshooting memo',
        'operator checklist',
        'rollback guide',
        'handoff blueprint'
    ),
    '$.campaigns.playbooks.article_structures_ru', JSON_ARRAY(
        'Проблема -> prerequisites -> точные шаги -> типовые фейлы -> проверка',
        'Цель -> стек -> внедрение -> код/настройки -> rollback-план',
        'Контекст кейса -> сетап -> метрики -> узкие места -> переиспользуемый шаблон',
        'Чеклист -> стек -> действия -> QA -> заметки по масштабу -> итог',
        'Что сломалось -> как диагностировать -> как чинить -> как проверить -> как не словить снова',
        'Задача оператора -> минимальный рабочий сетап -> edge cases -> handoff -> итоговый SOP'
    ),
    '$.campaigns.playbooks.article_user_prompt_append_ru', 'Смещай акцент в сторону практической реализации, troubleshooting, SOP, handoff, rollback, QA и точных шагов оператора. Если тема уже была, меняй угол: другой failure mode, другой этап пайплайна, другой сценарий запуска, другой тип команды.',

    '$.campaigns.signals.daily_min', 4,
    '$.campaigns.signals.daily_max', 10,
    '$.campaigns.signals.max_per_run', 4,
    '$.campaigns.signals.duplicate_retry_attempts', 4,
    '$.campaigns.signals.word_min', 1400,
    '$.campaigns.signals.word_max', 3000,
    '$.campaigns.signals.styles_ru', JSON_ARRAY(
        'policy brief',
        'обзор сигнала рынка',
        'регуляторная записка',
        'сводка изменений платформ',
        'policy-impact memo',
        'operator checklist',
        'что делать сейчас',
        'enforcement watch',
        'risk memo',
        'compliance update',
        'операционный bulletin',
        'разбор последствий для команды',
        'regulatory watch',
        'impact dispatch'
    ),
    '$.campaigns.signals.clusters_ru', JSON_ARRAY(
        'изменения policy в Meta и ужесточение модерации',
        'сдвиги Telegram, правила монетизации и новые ограничения',
        'ограничения TikTok Ads и апдейты commerce-экосистемы',
        'регуляторные движения в СНГ и их эффект на affiliate-рынок',
        'privacy-сдвиги в мире и последствия для атрибуции',
        'сигналы по payment, compliance и волатильности источников',
        'сдвиги trust-механик и давление на качество аккаунтов',
        'волатильность источников после новых правил модерации',
        'потери измерения после privacy-ограничений и data retention сдвигов',
        'Telegram enforcement-паттерны для affiliate-команд',
        'что первым меняется для баеров после platform shifts',
        'операционный response plan при резких ограничениях платформ',
        'свежие политические новости и решения власти с влиянием на рынок трафика',
        'бизнес-аналитика по компаниям, секторам и рыночному стрессу',
        'аналитика бирж, структуры рынка и движения ликвидности',
        'отдельные криптовалюты и их новостной фон как рыночный сигнал',
        'свежие бизнес-новости России с последствиями для digital-рынка',
        'новости законодательства России, законопроекты и практика применения'
    ),
    '$.campaigns.signals.article_structures_ru', JSON_ARRAY(
        'Сигнал -> что изменилось -> влияние на оператора -> затронутые гео -> чеклист действий',
        'Policy-апдейт -> паттерн enforcement -> скрытые риски -> план реакции',
        'Новость -> почему это важно -> кто почувствует первым -> шаги смягчения',
        'Policy-impact memo -> что изменилось -> что ломается -> что делать сейчас',
        'Regulatory watch -> краткий сигнал -> карта рисков -> чеклист реакции',
        'Operator checklist -> немедленные действия -> edge cases -> верификация',
        'Что делать сейчас -> сигнал -> последствия -> план на первые 24 часа',
        'Enforcement watch -> симптом -> механизм давления -> кто под ударом -> как перестроиться'
    ),
    '$.campaigns.signals.article_user_prompt_append_ru', 'Отслеживай policy, модерацию, регуляторику и рыночные сигналы вокруг арбитража трафика. В этот же слой включай свежие политические новости, бизнес-аналитику, аналитику бирж, движения по отдельным криптовалютам, бизнес-новости России и новости законодательства России, если у них есть реальное последствие для digital-рынка, affiliate-операций, платежей, комплаенса, источников трафика или поведения платформ. Принудительно смещай угол в policy-impact memo, regulatory watch, operator checklist, enforcement watch или формат «что делать сейчас», а не в очередной общий обзор. Каждый материал должен отвечать на вопросы: что изменилось, кто почувствует удар первым, что ломается в операционке и что команде делать дальше.',

    '$.campaigns.fun.daily_min', 2,
    '$.campaigns.fun.daily_max', 6,
    '$.campaigns.fun.max_per_run', 3,
    '$.campaigns.fun.duplicate_retry_attempts', 3,
    '$.campaigns.fun.word_min', 1000,
    '$.campaigns.fun.word_max', 2400,
    '$.campaigns.fun.styles_ru', JSON_ARRAY(
        'сатирический памфлет',
        'юмористический обзор',
        'мем-редакционка',
        'операционная пародия',
        'заметка про офисный фольклор',
        'комическая backstage-колонка',
        'фельетон ниши',
        'мемный постмортем',
        'иронический разбор роли',
        'редакционная шутка с фактами'
    ),
    '$.campaigns.fun.article_structures_ru', JSON_ARRAY(
        'Сетап -> абсурдное обострение -> панчлайн -> нишевая правда',
        'Портрет персонажа -> операционный хаос -> мемный payoff -> вывод',
        'Пародийный обзор -> преувеличение -> реальные боли -> финальный укол',
        'Сцена из команды -> цепочка нелепостей -> знакомая боль -> честный вывод',
        'Мемный кейс -> крэш реальности -> backstage-правда -> короткий takeaway'
    ),
    '$.campaigns.fun.article_user_prompt_append_ru', 'Держи тон живым, ироничным и нишевым. Юмор должен рождаться из реальной affiliate-операционки, ролевого поведения команды, handoff-сбоев, модерационного абсурда и хаоса трекеров, а не из общих шуток.'
)
ORDER BY id DESC
LIMIT 1;
