CREATE TABLE IF NOT EXISTS public_cases (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    domain_host VARCHAR(190) NOT NULL DEFAULT '',
    lang_code VARCHAR(8) NOT NULL DEFAULT 'en',
    title VARCHAR(255) NOT NULL DEFAULT '',
    slug VARCHAR(190) NOT NULL DEFAULT '',
    symbolic_code VARCHAR(190) NOT NULL DEFAULT '',
    client_name VARCHAR(255) NOT NULL DEFAULT '',
    industry_summary VARCHAR(255) NOT NULL DEFAULT '',
    period_summary VARCHAR(255) NOT NULL DEFAULT '',
    role_summary VARCHAR(255) NOT NULL DEFAULT '',
    stack_summary VARCHAR(255) NOT NULL DEFAULT '',
    problem_summary VARCHAR(255) NOT NULL DEFAULT '',
    result_summary VARCHAR(255) NOT NULL DEFAULT '',
    seo_title VARCHAR(255) NOT NULL DEFAULT '',
    seo_description VARCHAR(255) NOT NULL DEFAULT '',
    excerpt_html TEXT NULL,
    challenge_html MEDIUMTEXT NULL,
    solution_html MEDIUMTEXT NULL,
    architecture_html MEDIUMTEXT NULL,
    results_html MEDIUMTEXT NULL,
    metrics_html MEDIUMTEXT NULL,
    deliverables_html MEDIUMTEXT NULL,
    sort_order INT NOT NULL DEFAULT 100,
    is_published TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_public_cases_domain_lang_slug (domain_host, lang_code, slug),
    UNIQUE KEY uniq_public_cases_domain_lang_symbolic_code (domain_host, lang_code, symbolic_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO public_cases (domain_host,lang_code,title,slug,symbolic_code,client_name,industry_summary,period_summary,role_summary,stack_summary,problem_summary,result_summary,seo_title,seo_description,excerpt_html,challenge_html,solution_html,architecture_html,results_html,metrics_html,deliverables_html,sort_order,is_published,created_at,updated_at) VALUES
('', 'ru', 'Создание ANTIFRAUD TRACKER для ограничения доступа ботов к офферу', 'antifraud-tracker-bot-offer-protection', 'antifraud-tracker', 'Adtech / affiliate product', 'Антифрод и adtech', '2025-2026', 'Архитектура, backend, аналитика, anti-abuse логика', 'PHP, MySQL, event tracking, rules engine, admin workflows', 'Оффер получал нецелевой бот-трафик, из-за чего рос риск блокировок, искажалась аналитика и страдала окупаемость закупки.', 'Собран рабочий ANTIFRAUD TRACKER, который отделяет подозрительные паттерны, ограничивает доступ ботов к офферу и даёт команде прозрачный контур принятия решений.', 'Кейс ANTIFRAUD TRACKER: защита оффера от ботов и контроль anti-fraud трафика', 'Разработка ANTIFRAUD TRACKER для защиты оффера от ботов: антифрод-логика, события, сегментация трафика, ограничения доступа и управляемая аналитика.', '<p>Разработан ANTIFRAUD TRACKER для защиты оффера от ботов, очистки трафика и повышения управляемости anti-fraud решений.</p>', '<p>На стороне оффера накапливался бот-трафик, который искажал воронку, нагружал инфраструктуру и повышал риск ограничений со стороны партнёров. Задача состояла в построении управляемой anti-fraud системы, а не в наборе разрозненных блокировок.</p>', '<p>Мы декомпозировали точки входа, собрали сигналы, спроектировали скоринг риска, ограничения доступа и сценарии ручной валидации. Внедрение шло итерационно: логирование, сегментация, правила, отчётность и калибровка.</p>', '<p>Решение опиралось на событийную модель: сбор технических и поведенческих сигналов, агрегирование профиля риска, rules engine с порогами и административный контур для анализа спорных паттернов и управления исключениями.</p>', '<p>Оффер получил более чистый трафик, предсказуемый режим работы и прозрачные причины ограничений. Команда стала быстрее адаптироваться к новым паттернам обхода и лучше контролировать качество входящего потока.</p>', '<ul><li>Снижение доли подозрительных визитов.</li><li>Повышение точности аналитики.</li><li>Сокращение ручной реакции на инциденты.</li><li>Управляемые ограничения доступа без массовых ложных блокировок.</li></ul>', '<ul><li>Сбор и нормализация anti-fraud сигналов.</li><li>Скоринг и rules engine.</li><li>Ограничение доступа к офферу.</li><li>Административный интерфейс и отчётность.</li></ul>', 10, 1, NOW(), NOW()),
('', 'ru', 'Подготовка MVP для аналитической админки', 'analytics-admin-mvp', 'analytics-admin-mvp', 'B2B digital product', 'Аналитика и внутренние продукты', '2026', 'Product discovery, архитектура, backend, UI для внутренних команд', 'PHP, MySQL, event storage, dashboards, filters, attribution logic', 'Команде был нужен MVP аналитической админки, который быстро даст видимость по трафику, лидам и эффективности ключевых разделов без длительной BI-разработки.', 'Собран MVP аналитической админки с дашбордами, источниками трафика, логами, сегментацией и базовой воронкой для операционного управления.', 'Кейс MVP аналитической админки: быстрый запуск dashboards и управляемой аналитики', 'Разработка MVP аналитической админки: дашборды, воронка, логи, сегментация трафика и управляемая операционная аналитика для B2B продукта.', '<p>Подготовили MVP аналитической админки, чтобы команда получила рабочий инструмент для ежедневного управления трафиком, лидами и качеством источников.</p>', '<p>До запуска данные были разрозненными: часть метрик жила в логах, часть в отдельных таблицах, а единая картина по трафику, ботам, заявкам и конверсии собиралась вручную. Это замедляло решения и реакцию на аномалии.</p>', '<p>Мы сформировали MVP вокруг операционных сценариев: что команде нужно видеть каждый день, какие вопросы должны закрываться без разработчика и какие события нужно фиксировать сразу. На этой основе собрали дашборды, таблицы, фильтры и базовую атрибуцию.</p>', '<p>Решение строилось от данных к интерфейсу: нормализация визитов и lead-событий, агрегаты для дешёвого чтения, представления по разделам, устройствам, странам и источникам. Это создало основу для дальнейшего развития аналитической платформы.</p>', '<p>MVP дал команде рабочую точку контроля: появилась прозрачность по трафику, ботам, воронке и качеству каналов. Часть вопросов ушла из ручных выгрузок в ежедневную работу через админку.</p>', '<ul><li>Сокращение времени на разбор трафика и лидов.</li><li>Быстрое выявление аномалий.</li><li>Прозрачная воронка.</li><li>Основа для масштабирования в полноценную аналитическую платформу.</li></ul>', '<ul><li>Дашборд с KPI.</li><li>Разрезы по источникам, устройствам и странам.</li><li>Логи визитов и lead-событий.</li><li>Базовая атрибуция и фильтры.</li></ul>', 20, 1, NOW(), NOW()),
('', 'ru', 'Рефакторинг проекта на 1С-Битрикс: обмен с 1С, каталог, фильтры, desktop и mobile', 'bitrix-refactoring-1c-catalog-filters', 'bitrix-refactor', 'E-commerce / legacy platform', 'E-commerce и корпоративные сайты', '2025-2026', 'Технический аудит, refactoring, интеграции, frontend delivery', '1C-Bitrix, 1C integration, catalog logic, search filters, responsive frontend', 'Проект на 1С-Битрикс тормозил развитие: устаревший обмен с 1С, сложный каталог, нестабильные фильтры и рассинхрон между desktop и mobile версиями сайта.', 'Проведён системный рефакторинг Bitrix-проекта: перестроен обмен с 1С, обновлена логика каталога и фильтров, приведены к единому уровню desktop и mobile версии.', 'Кейс рефакторинга 1С-Битрикс: обмен с 1С, каталог, фильтры и адаптивный frontend', 'Рефакторинг проекта на 1С-Битрикс: модернизация обмена с 1С, каталога, фильтров и desktop/mobile версии сайта для устойчивой e-commerce работы.', '<p>Выполнили рефакторинг проекта на 1С-Битрикс, в рамках которого переработали обмен с 1С, каталог, фильтры и пользовательский интерфейс для desktop и mobile.</p>', '<p>Старая версия проекта ограничивала рост: обмен с 1С был хрупким, каталог содержал накопленный технический долг, фильтры работали нестабильно, а desktop и mobile развивались как разные продукты.</p>', '<p>Работу начали с технического аудита и картирования критичных сценариев, после чего поэтапно стабилизировали интеграционный контур, логику каталога, фильтры и интерфейсные слои. Такой порядок позволил снижать риск поломки бизнес-процессов.</p>', '<p>Рефакторинг включал перепроектирование обмена с 1С, упрощение зависимостей внутри каталога, нормализацию данных для фильтрации и выравнивание шаблонов интерфейса между desktop и mobile. Целью была предсказуемая система сопровождения, а не только визуальное обновление.</p>', '<p>Сайт стал устойчивее и удобнее для развития: обмен с 1С получил более надёжный контур, каталог и фильтры стали лучше поддерживать рост номенклатуры, а пользовательский опыт перестал зависеть от устройства.</p>', '<ul><li>Снижение операционного риска в обмене с 1С.</li><li>Улучшение управляемости каталога и фильтрации.</li><li>Сокращение числа регрессий между desktop и mobile.</li><li>Повышение скорости дальнейших доработок.</li></ul>', '<ul><li>Рефакторинг обмена с 1С.</li><li>Перестройка каталога.</li><li>Обновление фильтров.</li><li>Выравнивание desktop и mobile версий.</li></ul>', 30, 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    client_name = VALUES(client_name),
    industry_summary = VALUES(industry_summary),
    period_summary = VALUES(period_summary),
    role_summary = VALUES(role_summary),
    stack_summary = VALUES(stack_summary),
    problem_summary = VALUES(problem_summary),
    result_summary = VALUES(result_summary),
    seo_title = VALUES(seo_title),
    seo_description = VALUES(seo_description),
    excerpt_html = VALUES(excerpt_html),
    challenge_html = VALUES(challenge_html),
    solution_html = VALUES(solution_html),
    architecture_html = VALUES(architecture_html),
    results_html = VALUES(results_html),
    metrics_html = VALUES(metrics_html),
    deliverables_html = VALUES(deliverables_html),
    sort_order = VALUES(sort_order),
    is_published = VALUES(is_published),
    updated_at = NOW();
