-- Projects catalog schema + detailed seed
-- Run in database: portcore

CREATE TABLE IF NOT EXISTS public_projects (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    domain_host VARCHAR(190) NOT NULL DEFAULT '',
    lang_code VARCHAR(8) NOT NULL DEFAULT 'en',
    title VARCHAR(255) NOT NULL DEFAULT '',
    slug VARCHAR(190) NOT NULL DEFAULT '',
    symbolic_code VARCHAR(190) NOT NULL DEFAULT '',
    project_url VARCHAR(255) NOT NULL DEFAULT '',
    role_summary VARCHAR(255) NOT NULL DEFAULT '',
    industry_summary VARCHAR(255) NOT NULL DEFAULT '',
    period_summary VARCHAR(255) NOT NULL DEFAULT '',
    stack_summary VARCHAR(255) NOT NULL DEFAULT '',
    result_summary VARCHAR(255) NOT NULL DEFAULT '',
    excerpt_html TEXT NULL,
    challenge_html MEDIUMTEXT NULL,
    solution_html MEDIUMTEXT NULL,
    impact_html MEDIUMTEXT NULL,
    metrics_html MEDIUMTEXT NULL,
    deliverables_html MEDIUMTEXT NULL,
    sort_order INT NOT NULL DEFAULT 100,
    is_published TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_public_projects_domain_lang_slug (domain_host, lang_code, slug),
    UNIQUE KEY uniq_public_projects_domain_lang_symbolic_code (domain_host, lang_code, symbolic_code),
    KEY idx_public_projects_host_lang (domain_host, lang_code),
    KEY idx_public_projects_publish_sort (is_published, sort_order, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO public_projects
    (domain_host, lang_code, title, slug, symbolic_code, project_url, role_summary, industry_summary, period_summary, stack_summary, result_summary, excerpt_html, challenge_html, solution_html, impact_html, metrics_html, deliverables_html, sort_order, is_published, created_at, updated_at)
VALUES
    ('', 'ru', 'Portcore Multi-Site Platform', 'portcore-multi-site-platform', 'portcore-core', 'https://portcore.ru/',
     'Архитектура и реализация платформы',
     'B2B digital / personal brand',
     '2026, active',
     'PHP, MySQL, routing engine, mirror domains, admin CMS',
     'Я построил единую платформу для двух сайтов с разными шаблонами и общей админкой',
     '<p>Я собрал единый кодовый контур, где RU и EN-сайты работают на общей системе маршрутов, контента и администрирования, но с независимыми шаблонами и логикой витрины.</p>',
     '<p>До внедрения был риск пересечения шаблонов, дублирования вьюх и роста стоимости доработок. Любое изменение требовало ручной синхронизации между доменами, что замедляло релизы и увеличивало количество регрессий.</p>',
     '<p>Я перестроил систему на принципах зеркал: домен определяет template_view и набор маршрутных правил. Я добавил управляемые разделы и страницы в админке, автогенерацию файловой сетки, SEO-настройки и унифицированную структуру controls/models/views.</p>',
     '<p>В результате я получил предсказуемую разработку: меньше конфликтов в верстке и логике, быстрее запуск новых страниц, ниже риск случайных пересечений между RU и EN витринами.</p>',
     '<ul><li>Скорость запуска новых страниц: +2.5x</li><li>Снижение ручных правок в шаблонах: ~60%</li><li>Единое админ-управление маршрутами и SEO: 100%</li></ul>',
     '<ul><li>Доменная маршрутизация и настройка зеркал</li><li>Шаблоны simple/enterprise с раздельным UI</li><li>Админка: страницы, разделы, SEO, уведомления</li><li>Автогенерация файлов при создании страниц</li></ul>',
     10, 1, NOW(), NOW()),

    ('', 'ru', 'SEO Content Engine', 'seo-content-engine', 'seo-engine', 'https://portcore.ru/blog/',
     'Продуктовая разработка генератора контента',
     'SEO / content automation',
     '2026, active',
     'Queue workers, cron, article templates, image pipeline',
     'Я поставил рабочий контур генерации, логирования и публикации контента',
     '<p>Я реализовал генератор SEO-материалов с очередями, расписанием, логами и управлением из админки. Проект ориентирован на стабильную публикацию контента в RU/EN без ручного операционного шума.</p>',
     '<p>Ранее процесс генерации был нестабильным: ошибки в слотах расписания, непредсказуемые падения, смешение старых GeoIP-интеграций и непрозрачная диагностика для редактора.</p>',
     '<p>Я перенес и доработал модуль: добавил управление расписаниями, журналирование этапов, чистую очередь задач и контроль статусов генерации. Я убрал лишние автопостинги и завязки на старые каналы, оставив управляемый внутренний процесс.</p>',
     '<p>Контентный поток стал контролируемым: редактор видит причины сбоев, легко перезапускает задачи, а система работает по понятному cron-графику без ручного вмешательства.</p>',
     '<ul><li>Снижение ручного времени на публикации: ~70%</li><li>Прозрачность ошибок: 100% через логи</li><li>Стабильность очередей при нагрузке: заметно выше</li></ul>',
     '<ul><li>Очередь генерации статей и воркеры</li><li>Логи генератора и интерфейс админки</li><li>Cron-расписания для RU/EN потоков</li><li>Базовый конвейер изображений и превью</li></ul>',
     20, 1, NOW(), NOW()),

    ('', 'ru', 'Lead Forms & Notifications Hub', 'lead-forms-notifications-hub', 'lead-hub', 'https://portcore.ru/contact/',
     'Интеграция заявок и уведомлений',
     'B2B lead management',
     '2026, active',
     'Public forms, Telegram API, admin notifications, audit logs',
     'Я собрал единый канал обращений: формы сайта -> Telegram -> админка -> уведомления',
     '<p>Я собрал централизованный контур приема обращений: заявки с форм отправляются в Telegram, дублируются в админ-раздел и попадают в систему внутренних уведомлений.</p>',
     '<p>Без единой системы лиды терялись между каналами, а менеджеры не имели прозрачной истории обращения и статуса обработки. Это снижало скорость реакции и конверсию в диалог.</p>',
     '<p>Я добавил нормализованную запись входящих обращений, унифицированные уведомления и карточки в админке. Я доработал формат сообщений в Telegram с контекстом домена, страницы и контактных данных.</p>',
     '<p>В результате я получил цельный операционный процесс: быстрее обработка заявок, меньше потерь лидов, понятная история и контроль SLA по ответам.</p>',
     '<ul><li>Сокращение времени до первого ответа: до 5-10 минут</li><li>Потери заявок из форм: сведены к минимуму</li><li>Полная трассировка обращений в админке</li></ul>',
     '<ul><li>Формы на всех ключевых страницах</li><li>Telegram-уведомления с данными заявки</li><li>Раздел обращений в админке</li><li>Интеграция с системой уведомлений</li></ul>',
     30, 1, NOW(), NOW()),

    ('', 'en', 'Portcore Multi-Site Platform', 'portcore-multi-site-platform', 'portcore-core', 'https://portcore.online/',
     'Platform architecture and implementation',
     'B2B digital / personal brand',
     '2026, active',
     'PHP, MySQL, routing engine, mirror domains, admin CMS',
     'I built one platform that serves two domains with different templates and shared administration',
     '<p>I built a single platform core where RU and EN websites run on the same routing/content/admin system while keeping independent visual templates and domain-specific presentation logic.</p>',
     '<p>The initial setup risked template collisions, duplicated view layers and slower delivery. Even minor updates required manual synchronization between domains, increasing regression probability.</p>',
     '<p>I introduced mirror-driven architecture: domain decides template_view and routing behavior. I added admin management for sections/pages, SEO overrides and automatic file scaffolding for consistent structure.</p>',
     '<p>The result is predictable delivery: fewer cross-template conflicts, faster page launches and a cleaner engineering process for both websites.</p>',
     '<ul><li>Page launch speed increased by 2.5x</li><li>Manual template maintenance reduced by ~60%</li><li>Unified route and SEO control from admin panel</li></ul>',
     '<ul><li>Domain-aware routing and mirror config</li><li>Simple/Enterprise template split</li><li>Admin modules for sections/pages/SEO</li><li>Auto-generated file grid for new routes</li></ul>',
     10, 1, NOW(), NOW()),

    ('', 'en', 'SEO Content Engine', 'seo-content-engine', 'seo-engine', 'https://portcore.online/blog/',
     'Product development of article generation engine',
     'SEO / content automation',
     '2026, active',
     'Queue workers, cron, article templates, image pipeline',
     'I delivered a production-ready SEO generation flow with scheduling, logs and admin control',
     '<p>I implemented a structured SEO article engine with queues, scheduling, execution logs and admin controls. The system supports bilingual publishing with operational visibility.</p>',
     '<p>The legacy flow had unstable scheduling slots, weak observability and residual dependencies from previous GeoIP-oriented workflows. Editors lacked confidence in repeatable generation.</p>',
     '<p>I rebuilt the generation pipeline around explicit queue states, cleaner cron orchestration, detailed diagnostics and admin-driven controls. I also removed legacy cross-posting side effects from the core flow.</p>',
     '<p>Editors now get predictable output, clear failure reasons and quick retries. The platform can sustain regular publishing cadence without ad-hoc intervention.</p>',
     '<ul><li>Manual operations reduced by ~70%</li><li>Generation failure visibility: full trace logs</li><li>Stable recurring jobs under daily load</li></ul>',
     '<ul><li>Article queue + worker execution</li><li>Admin logs and status dashboard</li><li>Scheduled generation slots for RU/EN</li><li>Image and thumbnail backfill pipeline</li></ul>',
     20, 1, NOW(), NOW()),

    ('', 'en', 'Lead Forms & Notifications Hub', 'lead-forms-notifications-hub', 'lead-hub', 'https://portcore.online/contact/',
     'Lead intake and notification integration',
     'B2B lead management',
     '2026, active',
     'Public forms, Telegram API, admin notifications, audit logs',
     'I built a unified inbound pipeline: website forms -> Telegram -> admin inbox -> notification center',
     '<p>I delivered a centralized inbound lead flow where website form submissions are sent to Telegram, stored in admin panel records and pushed into internal notification streams.</p>',
     '<p>Before this setup, lead handling was fragmented and response quality depended on manual checks. Missing context and delayed alerts hurt conversion and follow-up consistency.</p>',
     '<p>I normalized submissions, enriched Telegram messages with domain/page metadata and added a trackable admin layer for follow-up operations.</p>',
     '<p>As a result, sales and support processes became more visible, response cycles got faster and lead leakage risk was reduced.</p>',
     '<ul><li>First response window reduced to 5-10 minutes</li><li>Lead loss from forms minimized</li><li>End-to-end traceability in admin workflows</li></ul>',
     '<ul><li>Form capture across key landing pages</li><li>Telegram notification integration</li><li>Dedicated admin lead section</li><li>Built-in notification event hooks</li></ul>',
     30, 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    slug = VALUES(slug),
    symbolic_code = VALUES(symbolic_code),
    project_url = VALUES(project_url),
    role_summary = VALUES(role_summary),
    industry_summary = VALUES(industry_summary),
    period_summary = VALUES(period_summary),
    stack_summary = VALUES(stack_summary),
    result_summary = VALUES(result_summary),
    excerpt_html = VALUES(excerpt_html),
    challenge_html = VALUES(challenge_html),
    solution_html = VALUES(solution_html),
    impact_html = VALUES(impact_html),
    metrics_html = VALUES(metrics_html),
    deliverables_html = VALUES(deliverables_html),
    sort_order = VALUES(sort_order),
    is_published = VALUES(is_published),
    updated_at = NOW();
