-- Add new service groups: MVP and E-com
-- Run in database: portcore

INSERT INTO public_services
    (domain_host, lang_code, service_group, title, slug, excerpt_html, content_html, sort_order, is_published, created_at, updated_at)
VALUES
    ('', 'ru', 'mvp', 'MVP для проверки продуктовой гипотезы', 'mvp-dlya-proverki-produktovoy-gipotezy',
     'Быстро собираем MVP с фокусом на проверку гипотезы, пользовательский фидбек и управляемый план развития.',
     '<p>Я проектирую MVP не как временную заглушку, а как технически здоровый первый релиз: минимальный набор сценариев, понятная метрика успеха и готовность к следующей итерации без переписывания с нуля.</p><p>Это позволяет быстрее выйти в рынок, собрать валидные сигналы от пользователей и принять решение о масштабировании на основе данных, а не предположений.</p>',
     480, 1, NOW(), NOW()),
    ('', 'en', 'mvp', 'MVP build for product hypothesis validation', 'mvp-build-for-product-hypothesis-validation',
     'Fast MVP delivery focused on hypothesis testing, early user feedback and controlled technical evolution.',
     '<p>I design MVPs as focused production-ready cores: essential user flows, measurable success criteria and a clean path for iterative expansion.</p><p>You get a fast market entry with lower product risk and clear decision points for scaling.</p>',
     490, 1, NOW(), NOW()),
    ('', 'ru', 'e-com', 'E-commerce платформа: конверсия и стабильность', 'e-commerce-platforma-konversiya-i-stabilnost',
     'Разработка и развитие e-com решений с упором на конверсию, скорость, интеграции и управляемые релизы.',
     '<p>Я строю e-commerce контур как системный продукт: каталог, карточки, корзина, checkout, платежи, заказы и сервисные интеграции работают как единая цепочка конверсии.</p><p>На практике это снижает потери в воронке, улучшает скорость запуска изменений и повышает предсказуемость коммерческих результатов.</p>',
     500, 1, NOW(), NOW()),
    ('', 'en', 'e-com', 'E-commerce platform engineering and growth', 'e-commerce-platform-engineering-and-growth',
     'E-commerce development with focus on conversion, performance, integrations and reliable release cycles.',
     '<p>I build and evolve e-commerce systems as conversion architecture: catalog, product pages, checkout flow, payment stack and order lifecycle integrated into one measurable funnel.</p><p>The result is steadier revenue operations, faster experimentation and lower failure risk during high-load periods.</p>',
     510, 1, NOW(), NOW()),

    ('', 'ru', 'mvp', 'MVP для B2B кабинета и ролей', 'mvp-dlya-b2b-kabineta-i-roley',
     'Собираем MVP личного кабинета с ролевой моделью, базовыми сценариями клиентов и готовностью к масштабированию.',
     '<p>Я проектирую минимально-достаточный кабинет: авторизация, роли, профиль, базовые операции и контроль доступа по контексту. В фокусе - запуск реального клиентского сценария, а не имитация интерфейса.</p><p>Такой MVP позволяет быстро проверить спрос и продуктовые допущения без лишней технической нагрузки.</p>',
     520, 1, NOW(), NOW()),
    ('', 'en', 'mvp', 'MVP for B2B account area and role model', 'mvp-for-b2b-account-area-and-role-model',
     'Lean MVP for account area with role-based access and production-focused core user scenarios.',
     '<p>I implement a practical account MVP: authentication, roles, profile, core actions and access boundaries. The delivery is optimized for real user validation, not just a visual prototype.</p><p>You can validate demand and usage behavior quickly with a clean path to extend functionality.</p>',
     530, 1, NOW(), NOW()),

    ('', 'ru', 'mvp', 'MVP маркетплейса услуг', 'mvp-marketpleysa-uslug',
     'Запуск MVP маркетплейса: каталог, заявки, отклики исполнителей и первичная модерация.',
     '<p>Я собираю MVP маркетплейса на ключевых транзакционных сценариях: публикация карточек, поиск, отклик, коммуникация и статус сделки. Сразу закладываются базовые anti-abuse и контроль качества контента.</p><p>Это дает возможность быстро протестировать модель монетизации и unit-экономику.</p>',
     540, 1, NOW(), NOW()),
    ('', 'en', 'mvp', 'Service marketplace MVP', 'service-marketplace-mvp',
     'Marketplace MVP with listings, lead flow, provider responses and initial moderation controls.',
     '<p>I build the marketplace around core transaction flow: listing, discovery, response, communication and status progression. Basic abuse controls and moderation are included from day one.</p><p>This enables fast monetization testing and data-backed prioritization.</p>',
     550, 1, NOW(), NOW()),

    ('', 'ru', 'mvp', 'MVP SaaS с оплатой подписки', 'mvp-saas-s-oplatoy-podpiski',
     'MVP SaaS-продукта с тарифами, биллингом, лимитами и базовой аналитикой активации.',
     '<p>Я реализую минимальный платежный контур: планы, подписка, лимиты и события жизненного цикла пользователя. Это позволяет измерять активацию, удержание и ранние сигналы churn.</p><p>Продукт запускается быстро и сразу дает полезные метрики для роста.</p>',
     560, 1, NOW(), NOW()),
    ('', 'en', 'mvp', 'SaaS MVP with subscription billing', 'saas-mvp-with-subscription-billing',
     'SaaS MVP with plans, subscription flow, usage limits and activation analytics.',
     '<p>I deliver a minimal but production-ready billing layer with plans, limits and lifecycle events. Teams can immediately measure activation, retention and early churn behavior.</p><p>This creates a clear growth baseline for roadmap decisions.</p>',
     570, 1, NOW(), NOW()),

    ('', 'ru', 'mvp', 'MVP внутренней операционной панели', 'mvp-vnutrenney-operacionnoy-paneli',
     'Разработка MVP админ-панели для операций: очереди задач, статусы, triage и SLA-контроль.',
     '<p>Я проектирую операционную панель вокруг реальных процессов команды: приоритеты, очереди, ответственные, эскалации и обзор узких мест. Интерфейс дает быстрый контроль вместо ручной координации в чатах.</p><p>Это снижает операционную турбулентность и ускоряет выполнение задач.</p>',
     580, 1, NOW(), NOW()),
    ('', 'en', 'mvp', 'Internal operations dashboard MVP', 'internal-operations-dashboard-mvp',
     'Operational dashboard MVP with task queues, triage, statuses and SLA visibility.',
     '<p>I build an operations-first dashboard: priorities, ownership, queue state and escalation points. The goal is faster execution control with less coordination overhead.</p><p>Your team gets predictable throughput and clearer accountability.</p>',
     590, 1, NOW(), NOW()),

    ('', 'ru', 'mvp', 'MVP для API-продукта и developer portal', 'mvp-dlya-api-produkta-i-developer-portal',
     'MVP API-сервиса: ключи, лимиты, базовая документация, логи запросов и onboarding разработчиков.',
     '<p>Я собираю API MVP с практичной DX-базой: выдача ключей, rate limits, первые endpointы, логирование и документация для быстрого старта интеграций. Это важно для раннего B2B adoption.</p><p>В результате вы быстрее проверяете интеграционный спрос и сценарии использования.</p>',
     600, 1, NOW(), NOW()),
    ('', 'en', 'mvp', 'API product MVP with developer portal', 'api-product-mvp-with-developer-portal',
     'API MVP with key issuance, usage limits, starter docs, request logs and developer onboarding.',
     '<p>I implement a practical API MVP foundation: keys, limits, initial endpoints, logging and quick-start docs. This accelerates integration trials and early B2B adoption.</p><p>You get faster signal on real API demand and usage patterns.</p>',
     610, 1, NOW(), NOW()),

    ('', 'ru', 'e-com', 'E-com checkout и снижение потерь', 'ecom-checkout-i-snizhenie-poter',
     'Оптимизируем checkout: формы, платежные шаги, ошибки и возврат в оплату для роста конверсии.',
     '<p>Я перестраиваю checkout как критическую конверсионную зону: минимизация трения, корректная обработка ошибок и быстрый повтор платежа. Дополнительно настраиваются события аналитики для точного контроля drop-off.</p><p>Это дает прямой коммерческий эффект в выручке и доле успешных оплат.</p>',
     620, 1, NOW(), NOW()),
    ('', 'en', 'e-com', 'E-commerce checkout optimization', 'ecommerce-checkout-optimization',
     'Checkout flow optimization to reduce drop-off and improve successful payment conversion.',
     '<p>I redesign checkout as a high-impact conversion layer: lower friction, better error handling and seamless payment retry. Detailed event tracking reveals exact friction points.</p><p>This improves conversion quality and revenue efficiency.</p>',
     630, 1, NOW(), NOW()),

    ('', 'ru', 'e-com', 'E-com каталог и smart-фильтры', 'ecom-katalog-i-smart-filtry',
     'Проектируем e-com каталог: фасеты, фильтры, SEO-логика и быстрый поиск по ассортименту.',
     '<p>Я строю каталог как навигационную и коммерческую систему: категории, фильтры, посадочные страницы и релевантный поиск. Это упрощает путь пользователя к покупке.</p><p>Параллельно усиливается органический трафик за счет корректной индексируемой структуры.</p>',
     640, 1, NOW(), NOW()),
    ('', 'en', 'e-com', 'E-commerce catalog and smart filters', 'ecommerce-catalog-and-smart-filters',
     'Catalog architecture with faceted filters, search relevance and SEO-ready navigation.',
     '<p>I design catalog systems for both discoverability and conversion: taxonomy, facets, search behavior and landing structures. Users find products faster, and pages perform better in organic channels.</p><p>This supports scalable assortment growth.</p>',
     650, 1, NOW(), NOW()),

    ('', 'ru', 'e-com', 'E-com интеграции: ERP, склад, логистика', 'ecom-integracii-erp-sklad-logistika',
     'Интегрируем e-com платформу с ERP, складом и доставкой для точных остатков и статусов заказов.',
     '<p>Я выстраиваю надежный обмен данными между витриной и операционными системами: остатки, цены, статусы, отгрузка, трекинг. Внедряются контуры идемпотентности и мониторинга ошибок.</p><p>Это снижает количество сбоев и повышает доверие клиентов к сервису.</p>',
     660, 1, NOW(), NOW()),
    ('', 'en', 'e-com', 'E-commerce integrations: ERP, warehouse, logistics', 'ecommerce-integrations-erp-warehouse-logistics',
     'Reliable integration layer for stock, pricing, order status and shipping flow synchronization.',
     '<p>I connect storefront and back-office systems with robust synchronization policies and error observability. Inventory, pricing and delivery status stay consistent across channels.</p><p>The business gets fewer incidents and higher operational trust.</p>',
     670, 1, NOW(), NOW()),

    ('', 'ru', 'e-com', 'E-com антифрод и риск-контроль', 'ecom-antifrod-i-risk-kontrol',
     'Внедряем risk-контур для e-com: проверка аномалий, защита от abuse и снижение chargeback.',
     '<p>Я добавляю в e-com процесс риск-сигналы и правила: поведенческие аномалии, гео/ASN-паттерны, сценарии step-up проверки и контроль подозрительных транзакций. Это снижает потери и нагрузку на ручной review.</p><p>Платформа становится устойчивее к abuse без заметного ущерба для UX.</p>',
     680, 1, NOW(), NOW()),
    ('', 'en', 'e-com', 'E-commerce fraud and risk controls', 'ecommerce-fraud-and-risk-controls',
     'Risk-control implementation for e-commerce: anomaly checks, abuse prevention and chargeback reduction.',
     '<p>I implement risk layers across checkout and account actions: anomaly rules, geo/network signals, step-up checks and suspicious transaction controls. The goal is lower fraud loss with controlled false positives.</p><p>You get safer revenue with stable customer experience.</p>',
     690, 1, NOW(), NOW()),

    ('', 'ru', 'e-com', 'E-com retention и повторные продажи', 'ecom-retention-i-povtornye-prodazhi',
     'Настройка retention-механик e-com: сегментация, сценарии возврата, персональные предложения и KPI повторных заказов.',
     '<p>Я проектирую retention-контур для роста LTV: сегменты клиентов, триггерные кампании, персональные офферы и аналитика повторных покупок. Сценарии строятся вокруг реального поведения, а не шаблонных рассылок.</p><p>Это повышает долю повторных продаж и устойчивость выручки.</p>',
     700, 1, NOW(), NOW()),
    ('', 'en', 'e-com', 'E-commerce retention and repeat purchase growth', 'ecommerce-retention-and-repeat-purchase-growth',
     'Retention architecture for repeat sales: segmentation, trigger flows, personalized offers and LTV metrics.',
     '<p>I build retention systems focused on behavior-driven segments, trigger campaigns and measurable repeat-purchase outcomes. The setup aligns marketing actions with product and operational data.</p><p>This improves customer lifetime value and revenue stability.</p>',
     710, 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE
    service_group = VALUES(service_group),
    title = VALUES(title),
    excerpt_html = VALUES(excerpt_html),
    content_html = VALUES(content_html),
    sort_order = VALUES(sort_order),
    is_published = VALUES(is_published),
    updated_at = NOW();
